/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

type JwtIssuerExpansion interface{}

type PolicyExpansion interface{}

type RoleExpansion interface{}
