apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: functions/alertmanager:0.15.0-rc.0-armhf
        imagePullPolicy: Always
        command: 
          - "alertmanager"
          - "--config.file=/alertmanager.yml"
          - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9003
          protocol: TCP
        resources:
          requests:
            memory: 25Mi
          limits:
            memory: 50Mi
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: openfaas
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
