apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: gateway
        image: openfaas/gateway:0.11.0-arm64
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "60s"
        - name: write_timeout
          value: "60s"
        - name: basic_auth
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 100Mi
      - name: faas-netesd
        image: openfaas/faas-netes:0.7.0-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
        env:
        - name: port
          value: "8081"
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "50s"
        - name: write_timeout
          value: "60s"
