apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "connector.name" . }}
    component: sns-connector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sns-connector