/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// JwtIssuerListerExpansion allows custom methods to be added to
// JwtIssuerLister.
type JwtIssuerListerExpansion interface{}

// JwtIssuerNamespaceListerExpansion allows custom methods to be added to
// JwtIssuerNamespaceLister.
type JwtIssuerNamespaceListerExpansion interface{}

// PolicyListerExpansion allows custom methods to be added to
// PolicyLister.
type PolicyListerExpansion interface{}

// PolicyNamespaceListerExpansion allows custom methods to be added to
// PolicyNamespaceLister.
type PolicyNamespaceListerExpansion interface{}

// RoleListerExpansion allows custom methods to be added to
// RoleLister.
type RoleListerExpansion interface{}

// RoleNamespaceListerExpansion allows custom methods to be added to
// RoleNamespaceLister.
type RoleNamespaceListerExpansion interface{}
