---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "builder.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pro-builder
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: pro-builder
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "builder.name" . }}
