# This component is licensed for OpenFaaS Standard/Enterprise customers only.
# Purchase or obtain a trial license at https://openfaas.com/pricing/

# You will need to create a license named "openfaas-license" - see the
# chart README for detailed instructions.

# Google cloud project ID
projectID: ""

# List if Pub/Sub subscriptions the connector should subscribe to.
subscriptions: []

# Kubernetes secret for the Google Cloud Application Default Credentials (ADC)
# to connect to Pub/Sub
gcpCredentialsSecret: gcp-pubsub-credentials

image: ghcr.io/openfaasltd/gcp-pubsub-connector:0.0.1

# The number of replicas of the connector.
replicas: 1

logs:
  # Log debug messages
  debug: false
  # Set the log format, supports console or json
  format: "console"

# Max timeout for a function
upstreamTimeout: 2m

# interval for rebuilding the map of functions and topics
rebuildInterval: 30s

# Use with slow consumers or long running functions.
asyncInvocation: false

# HTTP content-type for invoking functions
contentType: text/plain

# Print the data read from the Kafka topic before invoking functions
printRequestBody: false

# Print the HTTP status of invoked functions
printResponse: true

# Print the data received from invoked functions
printResponseBody: false

# Gateway URL to access API and for invocations
gatewayURL: http://gateway.openfaas:8080

# Basic auth for the gateway
basic_auth: true

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  # limits:
  #   memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}