/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openfaas/faas-netes/pkg/client/clientset/versioned/typed/iam/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIamV1 struct {
	*testing.Fake
}

func (c *FakeIamV1) JwtIssuers(namespace string) v1.JwtIssuerInterface {
	return &FakeJwtIssuers{c, namespace}
}

func (c *FakeIamV1) Policies(namespace string) v1.PolicyInterface {
	return &FakePolicies{c, namespace}
}

func (c *FakeIamV1) Roles(namespace string) v1.RoleInterface {
	return &FakeRoles{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIamV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
