apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headroom-controller.fullname" . }}
  labels:
    {{- include "headroom-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "headroom-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "headroom-controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headroom-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
{{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:8080
            - --metrics-secure=false
{{- end }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            - --leader-election-namespace={{ .Values.leaderElection.namespace | default .Release.Namespace }}
            {{- end }}
            {{- if eq .Values.rbac.role "Role" }}
            - --namespace={{ .Release.Namespace }}
            {{- end }}
            - --zap-log-level={{ .Values.logging.level }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
