apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "federated-gateway.name" . }}
    component: federated-gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "federated-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: federated-gateway