/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AppliedProfileApplyConfiguration represents an declarative configuration of the AppliedProfile type for use
// with apply.
type AppliedProfileApplyConfiguration struct {
	ProfileRef         *ResourceRefApplyConfiguration `json:"profileRef,omitempty"`
	ObservedGeneration *int64                         `json:"observedGeneration,omitempty"`
}

// AppliedProfileApplyConfiguration constructs an declarative configuration of the AppliedProfile type for use with
// apply.
func AppliedProfile() *AppliedProfileApplyConfiguration {
	return &AppliedProfileApplyConfiguration{}
}

// WithProfileRef sets the ProfileRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProfileRef field is set to the value of the last call.
func (b *AppliedProfileApplyConfiguration) WithProfileRef(value *ResourceRefApplyConfiguration) *AppliedProfileApplyConfiguration {
	b.ProfileRef = value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *AppliedProfileApplyConfiguration) WithObservedGeneration(value int64) *AppliedProfileApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
