/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AppliedProfileApplyConfiguration represents an declarative configuration of the AppliedProfile type for use
// with apply.
type AppliedProfileApplyConfiguration struct {
	Name                     *string `json:"name,omitempty"`
	Namespace                *string `json:"namespace,omitempty"`
	AppliedProfileGeneration *int64  `json:"appliedProfileGeneration,omitempty"`
}

// AppliedProfileApplyConfiguration constructs an declarative configuration of the AppliedProfile type for use with
// apply.
func AppliedProfile() *AppliedProfileApplyConfiguration {
	return &AppliedProfileApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AppliedProfileApplyConfiguration) WithName(value string) *AppliedProfileApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *AppliedProfileApplyConfiguration) WithNamespace(value string) *AppliedProfileApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithAppliedProfileGeneration sets the AppliedProfileGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliedProfileGeneration field is set to the value of the last call.
func (b *AppliedProfileApplyConfiguration) WithAppliedProfileGeneration(value int64) *AppliedProfileApplyConfiguration {
	b.AppliedProfileGeneration = &value
	return b
}
