/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FunctionStatusApplyConfiguration represents an declarative configuration of the FunctionStatus type for use
// with apply.
type FunctionStatusApplyConfiguration struct {
	Conditions []v1.Condition `json:"conditions,omitempty"`
}

// FunctionStatusApplyConfiguration constructs an declarative configuration of the FunctionStatus type for use with
// apply.
func FunctionStatus() *FunctionStatusApplyConfiguration {
	return &FunctionStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *FunctionStatusApplyConfiguration) WithConditions(values ...v1.Condition) *FunctionStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}
