/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FunctionStatusApplyConfiguration represents an declarative configuration of the FunctionStatus type for use
// with apply.
type FunctionStatusApplyConfiguration struct {
	Profiles []AppliedProfileApplyConfiguration `json:"profiles,omitempty"`
}

// FunctionStatusApplyConfiguration constructs an declarative configuration of the FunctionStatus type for use with
// apply.
func FunctionStatus() *FunctionStatusApplyConfiguration {
	return &FunctionStatusApplyConfiguration{}
}

// WithProfiles adds the given value to the Profiles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Profiles field.
func (b *FunctionStatusApplyConfiguration) WithProfiles(values ...*AppliedProfileApplyConfiguration) *FunctionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProfiles")
		}
		b.Profiles = append(b.Profiles, *values[i])
	}
	return b
}
