/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ResourceRefApplyConfiguration represents an declarative configuration of the ResourceRef type for use
// with apply.
type ResourceRefApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// ResourceRefApplyConfiguration constructs an declarative configuration of the ResourceRef type for use with
// apply.
func ResourceRef() *ResourceRefApplyConfiguration {
	return &ResourceRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceRefApplyConfiguration) WithName(value string) *ResourceRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ResourceRefApplyConfiguration) WithNamespace(value string) *ResourceRefApplyConfiguration {
	b.Namespace = &value
	return b
}
