apiVersion: v1
kind: Service
metadata:
  name: auth-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "connector.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: auth-proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: auth-proxy