/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	openfaasv1 "github.com/openfaas/faas-netes/pkg/apis/openfaas/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJwtIssuers implements JwtIssuerInterface
type FakeJwtIssuers struct {
	Fake *FakeOpenfaasV1
	ns   string
}

var jwtissuersResource = schema.GroupVersionResource{Group: "openfaas.com", Version: "v1", Resource: "jwtissuers"}

var jwtissuersKind = schema.GroupVersionKind{Group: "openfaas.com", Version: "v1", Kind: "JwtIssuer"}

// Get takes name of the jwtIssuer, and returns the corresponding jwtIssuer object, and an error if there is any.
func (c *FakeJwtIssuers) Get(ctx context.Context, name string, options v1.GetOptions) (result *openfaasv1.JwtIssuer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jwtissuersResource, c.ns, name), &openfaasv1.JwtIssuer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openfaasv1.JwtIssuer), err
}

// List takes label and field selectors, and returns the list of JwtIssuers that match those selectors.
func (c *FakeJwtIssuers) List(ctx context.Context, opts v1.ListOptions) (result *openfaasv1.JwtIssuerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jwtissuersResource, jwtissuersKind, c.ns, opts), &openfaasv1.JwtIssuerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &openfaasv1.JwtIssuerList{ListMeta: obj.(*openfaasv1.JwtIssuerList).ListMeta}
	for _, item := range obj.(*openfaasv1.JwtIssuerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jwtIssuers.
func (c *FakeJwtIssuers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jwtissuersResource, c.ns, opts))

}

// Create takes the representation of a jwtIssuer and creates it.  Returns the server's representation of the jwtIssuer, and an error, if there is any.
func (c *FakeJwtIssuers) Create(ctx context.Context, jwtIssuer *openfaasv1.JwtIssuer, opts v1.CreateOptions) (result *openfaasv1.JwtIssuer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jwtissuersResource, c.ns, jwtIssuer), &openfaasv1.JwtIssuer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openfaasv1.JwtIssuer), err
}

// Update takes the representation of a jwtIssuer and updates it. Returns the server's representation of the jwtIssuer, and an error, if there is any.
func (c *FakeJwtIssuers) Update(ctx context.Context, jwtIssuer *openfaasv1.JwtIssuer, opts v1.UpdateOptions) (result *openfaasv1.JwtIssuer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jwtissuersResource, c.ns, jwtIssuer), &openfaasv1.JwtIssuer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openfaasv1.JwtIssuer), err
}

// Delete takes name of the jwtIssuer and deletes it. Returns an error if one occurs.
func (c *FakeJwtIssuers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jwtissuersResource, c.ns, name), &openfaasv1.JwtIssuer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJwtIssuers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jwtissuersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &openfaasv1.JwtIssuerList{})
	return err
}

// Patch applies the patch and returns the patched jwtIssuer.
func (c *FakeJwtIssuers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *openfaasv1.JwtIssuer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jwtissuersResource, c.ns, name, pt, data, subresources...), &openfaasv1.JwtIssuer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*openfaasv1.JwtIssuer), err
}
