{{- if .Values.iam.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
{{- end }}