{{- if and .Values.asyncInvocation (gt (int .Values.async.maxInflight) 0) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "connector.fullname" . }}
    component: kafka-connector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "connector.name" . }}
    component: kafka-connector
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "connector.fullname" . }}
    component: kafka-connector
subjects:
  - kind: ServiceAccount
    name:  {{ template "connector.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ template "connector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
