/*
Copyright 2019-2021 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/openfaas/faas-netes/pkg/apis/openfaas/v1"
	openfaasv1 "github.com/openfaas/faas-netes/pkg/client/applyconfiguration/openfaas/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=openfaas.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("Function"):
		return &openfaasv1.FunctionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FunctionResources"):
		return &openfaasv1.FunctionResourcesApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FunctionSpec"):
		return &openfaasv1.FunctionSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("JwtIssuer"):
		return &openfaasv1.JwtIssuerApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("JwtIssuerSpec"):
		return &openfaasv1.JwtIssuerSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Policy"):
		return &openfaasv1.PolicyApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PolicySpec"):
		return &openfaasv1.PolicySpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PolicyStatement"):
		return &openfaasv1.PolicyStatementApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Profile"):
		return &openfaasv1.ProfileApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ProfileSpec"):
		return &openfaasv1.ProfileSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Role"):
		return &openfaasv1.RoleApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("RoleSpec"):
		return &openfaasv1.RoleSpecApplyConfiguration{}

	}
	return nil
}
