apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: gateway
        image: openfaas/gateway:0.9.2-armhf
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: read_timeout
          value: "60s"
        - name: write_timeout
          value: "60s"
        - name: basic_auth
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 100Mi
      - name: faas-netesd
        image: openfaas/faas-netes:0.6.0-armhf
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
          limits:
            memory: 50Mi
        env:
        - name: port
          value: "8081"
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "50s"
        - name: write_timeout
          value: "60s"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31112
  selector:
    app: gateway
