---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: openfaas
    component: queue-worker
  name: queue-worker
  namespace: "openfaas"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      labels:
        app: queue-worker
    spec:
      containers:
      - name:  queue-worker
        resources:
            requests:
              cpu: 50m
              memory: 120Mi
            
        image: openfaas/queue-worker:0.8.0-armhf
        imagePullPolicy: Always
        env:
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local"
        - name: faas_gateway_address
          value: "gateway.openfaas.svc.cluster.local"
        - name: "gateway_invoke"
          value: "true"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local"
        - name: ack_wait    # Max duration of any async task / request
          value: 60s
