{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
{{- if .Values.iam.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: oidc-plugin
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: oidc-plugin
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: oidc-plugin

{{- end }}
