{{- if .Values.iam.enabled }}
---

apiVersion: iam.openfaas.com/v1
kind: JwtIssuer
metadata:
  name: system
  namespace: openfaas
spec:
  iss: {{.Values.iam.systemIssuer.url}}
  aud:
  - {{.Values.iam.systemIssuer.url}}
  tokenExpiry: "30m"

{{- end }}
