/*
Copyright 2019-2020 OpenFaaS Authors

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openfaas/faas-netes/pkg/apis/openfaas/v1"
	"github.com/openfaas/faas-netes/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type OpenfaasV1Interface interface {
	RESTClient() rest.Interface
	FunctionsGetter
}

// OpenfaasV1Client is used to interact with features provided by the openfaas.com group.
type OpenfaasV1Client struct {
	restClient rest.Interface
}

func (c *OpenfaasV1Client) Functions(namespace string) FunctionInterface {
	return newFunctions(c, namespace)
}

// NewForConfig creates a new OpenfaasV1Client for the given config.
func NewForConfig(c *rest.Config) (*OpenfaasV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &OpenfaasV1Client{client}, nil
}

// NewForConfigOrDie creates a new OpenfaasV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *OpenfaasV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new OpenfaasV1Client for the given RESTClient.
func New(c rest.Interface) *OpenfaasV1Client {
	return &OpenfaasV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *OpenfaasV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
