---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gateway
  name: gateway
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: provider
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: provider
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: gateway
