---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfaas
    component: queue-worker
  name: queue-worker
  namespace: "openfaas"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: queue-worker
    spec:
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
      containers:
      - name:  queue-worker
        resources:
            requests:
              cpu: 50m
              memory: 120Mi
        image: ghcr.io/openfaas/queue-worker:0.14.0
        imagePullPolicy: Always
        env:
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local"
        - name: faas_nats_channel
          value: "faas-request"
        - name: faas_nats_queue_group
          value: "faas"
        - name: faas_gateway_address
          value: "gateway.openfaas.svc.cluster.local"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local"
        - name: ack_wait
          value: "60s"
        - name: max_inflight
          value: "50"
        # OpenFaaS PRO license required
        - name: "max_retry_attempts"
          value: "10"
        - name: "max_retry_wait"
          value: "120s"
        - name: "initial_retry_wait"
          value: "10s"
        - name: "retry_http_codes"
          value: "408,429,500,502,503,504"
        - name: print_request_body
          value: "false"
        - name: print_response_body
          value: "false"
        - name: secret_mount_path
          value: "/var/secrets/gateway"
        - name: basic_auth
          value: "true"
        volumeMounts:
        - name: auth
          readOnly: true
          mountPath: "/var/secrets/gateway"
